#!/usr/bin/env bash
# This configures a new ubuntu machine byy installing
# the Nginx where it should be listening on port 80
# And Serve a page that would return a Hello World string
#
# the colors
blue='\e[1;34m'
brown='\e[0;33m'
green='\e[1;32m'
reset='\033[0m'

echo -e "${blue}Updating and installing ${brown}Nginx${blue}.${reset}\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\n${blue}Setting up some minor stuff.${reset}\n"

# when starting nginx service
sudo service nginx start

# when allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# The Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# For Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# When restarting nginx
sudo service nginx restart

echo -e "\n${green}Completed.${reset} ✅\n"
